/**
 * Generates generated/prefab-props.ts from the catalogue: a `PrefabProps` interface with each
 * prefab's logic properties, so `sim().device(key, prefab, props)` is type-checked and the editor
 * shows each property's description, Read/Write and modes.
 */
import type { Access, Catalog, CatalogPrefab } from "./catalog.ts";

const ACCESS: Record<Access, string> = { r: "read-only", w: "write-only", rw: "read, write" };

/** Text safe inside a JSDoc comment. */
function doc(text: string): string {
	return text.replace(/\*\//g, "*\\/").replace(/\s+/g, " ").trim();
}

function propertyDoc(catalog: Catalog, prefab: CatalogPrefab, name: string, access: Access): string {
	const parts = [catalog.logicTypes[name]?.text, `(${ACCESS[access]})`];
	if (name === "Mode" && prefab.modes.length) {
		parts.push(`Modes: ${prefab.modes.map((m, i) => `${i} ${m}`).filter((m) => !m.endsWith(" ")).join(", ")}.`);
	}
	return doc(parts.filter(Boolean).join(" "));
}

export function prefabPropsSource(catalog: Catalog): string {
	const lines = [
		"/* Generated by `npm run catalog:build` from the device catalogue. Do not edit. */",
		"",
		"/** Each prefab's logic properties, as `sim().device()` takes them. */",
		"export interface PrefabProps {",
	];
	const prefabs = Object.values(catalog.prefabs).sort((a, b) => a.prefab.localeCompare(b.prefab));
	for (const prefab of prefabs) {
		const from = prefab.source === "mod" ? ", from a mod" : "";
		lines.push(`\t/** ${doc(prefab.title)} (hash ${prefab.hash}${from}) */`);
		lines.push(`\t${JSON.stringify(prefab.prefab)}: {`);
		for (const [name, access] of Object.entries(prefab.logic).sort(([a], [b]) => a.localeCompare(b))) {
			lines.push(`\t\t/** ${propertyDoc(catalog, prefab, name, access)} */`);
			lines.push(`\t\t${name}?: number;`);
		}
		lines.push("\t};");
	}
	lines.push("}", "");
	return lines.join("\n");
}
